id: b5fb79e2-89cb-5ce3-af48-33493e40eccc
name: AWS Config
type: product
ownerId: 00000000-0000-0000-0000-000000000000
created: '2024-06-18T19:20:13.234Z'
updated: '2024-06-18T21:54:59.447Z'
code: config
status: active
description: AWS Config
logo: https://cdn.auditmation.io/logos/amazon-aws-config.svg
url: https://docs.aws.amazon.com/config/latest/APIReference/Welcome.html
vendorId: 9b45d05a-b570-5007-8e0c-8ebac2ea4095
vendorCode: amazon
parentType: suite
suiteId: bfa91d14-4436-5d41-815f-da7faa67ea6a
suiteCode: aws
tags: []
factoryTypes:
- software
hostingTypes: []
managedServiceTypes: []
environment: dev
hostname: https://api.dev.crunch.zerobias.com:443
cpeProducts:
- amazon:web_services_config
- amazon:aws_config
